### ISSUE TITLE
[REQ] rutor.org

### ISSUE THREAD

**Issue by Sky-er** [zone117x/Jackett#119]
Dear sir,

Please, add russian tracker http://rutor.org
It's a free torrent tracker, without having to register.

WBR,
Sky-er

**Comment by Kayomani** [comment]
Implemented in 167bfd303c3b0d5d4620a06c997c6f9a206b2607, will be in the next release.

I went off translations as I can't read Russian and I mapped tv to tv series and not tv.  Movies is mapped to foreign movies rather than our movies or sci fi movies.  I kinda thought you'd want those categories if you are using it with Sonarr or w/e so you'll have to let us know if you want the native  categories.

**Comment by d-lebed** [comment]
For some reason it does not return results while searching movies. I can see results in traced http source, but it does not return movies to couchpotato.

**Comment by m0thman** [comment]
Fixed in #197
