### ISSUE TITLE
Cant download on sonarr

### ISSUE THREAD

**Issue by djalmadicos** [zone117x/Jackett#164]
Pls help me, i am noob at english/ programing.
When i add tracker from jackett to sonarr i always get this:
![1](https://cloud.githubusercontent.com/assets/6911535/9595496/63db20ea-503d-11e5-9721-a530c88f7cc2.png)
![2](https://cloud.githubusercontent.com/assets/6911535/9595498/67117bd8-503d-11e5-91cb-e8a2ac3172c2.png)
![3](https://cloud.githubusercontent.com/assets/6911535/9595499/6aa11baa-503d-11e5-9fd0-c69471230d92.png)

**Comment by Kayomani** [comment]
Does it still fail for you? Looking at it now its a magnet file so Sonarr would not need to download anything.  It has been suggested it might have been previously a torrent file which is is perhaps blocked by your isp.  If the problem is still there then please repeat the above with debug logs enabled.

**Comment by Kayomani** [comment]
Let us know if its still failing..
