### ISSUE TITLE
T411 bug

### ISSUE THREAD

**Issue by maxcore** [zone117x/Jackett#185]
I dont know why but when i put my login pass i have this msg and i cant add the tracker 
![sans titre-1](https://cloud.githubusercontent.com/assets/4043787/10056836/012f20b0-620b-11e5-93bf-432b9843e72a.png)

**Comment by S1Lv3RskY** [comment]
Hi,
i have another error for t411 : 

2015-09-24 13:41:17.4606 Error Exception in test_indexer System.Net.WebException: Error getting response stream (ReadDone1): ReceiveFailure ---> System.IO.IOException: EndRead failure ---> System.Net.Sockets.SocketException: Connection reset by peer

maybe it's because t411.io change to t411.in ?

Thank you for your work

**Comment by spookssi** [comment]
T411 change his domaine extension... t411.IN not t411.IO ...

**Comment by Kayomani** [comment]
Domain has been updated already but will be delivered in the next release.

**Comment by raspdealer** [comment]
Is it possible to change this before your release ?

**Comment by Kayomani** [comment]
Fixed in released v0.6.7
