### ISSUE TITLE
Searches fail for specific shows

### ISSUE THREAD

**Issue by the-Dakta** [zone117x/Jackett#76]
So Jackett is working great with Sonarr for most shows, but there are a few different shows (Battlebots 2015 and @Midnight) that it won't find downloads for (Sonarr finds these fine on kat, but I'd rather not use that).

Anywho, here are the errors:

15-7-1 11:55:53.5|Error|Torznab|An error occurred while processing feed. http://[REDACTED]/api/iptorrents/api?t=tvsearch&cat=5030,5040,22,73,4,5,79,83,65,82,66,25,24,23,78,26,173&extended=1&apikey=<removed>&offset=0&limit=100&rid=38478&season=2015&ep=05/14

System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at NzbDrone.Core.Indexers.Torznab.TorznabRssParser.PreProcess(IndexerResponse indexerResponse) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\Torznab\TorznabRssParser.cs:line 16
   at NzbDrone.Core.Indexers.RssParser.ParseResponse(IndexerResponse indexerResponse) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\RssParser.cs:line 40
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 204
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(IList`1 pageableRequests) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 131

My url is ugly because I've added all of the TV categories from IPT in an attempt to help it find these items, but with no luck. I thought originally that the issue was because @midnight is a daily show, but was proven wrong when I had the same issue with Battlebots and others.

**Comment by the-Dakta** [comment]
So by inputting the URL into my browser, I get this error:

"Input string was not in a correct format."

I haven't been able to figure this out for this @midnight query, but I found that it was searching for Season 6 of Battlebots instead of season 1. I suspect this is the case for most of the other shows as well, but I'm unsure what's up with @midnight.

**Comment by the-Dakta** [comment]
It seems the same thing is happening with Morethan.tv set up as well.

**Comment by damwthomas** [comment]
I'd look into this, but I do not have an account so I can't really test anything

**Comment by the-Dakta** [comment]
After some more testing, I've confirmed that (at least for these titles), the issue is the same on TPB even. It seems that there's some miscommunication between Sonarr and Jackett about the Season/Episode number for these items. Out of the shows I've added, the issue persists across all of these shows: Battlebots, Bob's Burgers, Lucas Bros. Moving Company, and @midnight.

**Comment by damwthomas** [comment]
So I've been doing some tests on TPB for the last 2 hours, what I've found out:

Battlebots is not a well known show and only has 5 results (even with a manual search)
Bob's burgers, can't be found because of the ' sign in the name

@midnight, hasn't given me results for several reasons:
- Several urls are created to search indexers and they add 'S' (for season) + the season number (which in this case is 2013 for the first season), so naturaly this gives an empty search result.
- Take the added 'S' away, this doesn't give any results on TPB
- Take '2013' out of the query, you get only see results of season 2014

Now, why doesn't it find season 2 (aka 2014):
- again, the search string is 'at midnight s2014', doesn't give a result
- Without the 'S', you get results. But what do they look like:
* at.midnight.2014.01.09.hdtv....
*at.midnight.2014.04.22....
*at.midnight.2014.10.30.....

My guess is, sonar just doesn't recognize these episode patterns. Which would explain why the 260 results I gave sonarr resulted in 0 downloaded.

What can we do:
- Seeing as we don't even get results on TPB from a manual search for non well known shows, there's nothing much we can do about that.
- The Bob's Burgers problem is something we can fix and is something I'll be working on later this week. 
- The @midnight problem, again we can't do much about that, since we're giving results to sonar, but it just doesn't recognize the pattern.

(Haven't had the time to why kat does give you results)

**Comment by the-Dakta** [comment]
Thanks for the update! I completely understand not bothering with lesser known shows, but I thought that Sonarr (and subsequently Jackett), used the TVRage ID to perform the searches, only falling back on the name if the ID found nothing.

If it helps at all, I've grabbed the actual API request url from that error and used in directly in the browser for a few tests. When I modify the Battlebots search (from Season 6 to Season 1), it gives me a page of XML with results. For @midnight, no modification will find it.

**Comment by damwthomas** [comment]
The tvrageid is used on sites that support it. We can't search on TPB for example with it, because TPB just doesn't have a tvrageid anywhere on it.

Btw, can I ask why you rather not use kat?

(ps: you might want to secure that moontube url)

**Comment by the-Dakta** [comment]
That makes sense.

I'd rather not use a public tracker. I've had bad experiences in the past.

(redacted, thanks)

**Comment by the-Dakta** [comment]
So it seems that the special characters are exactly what's causing the issue, since it just takes the show name from Sonarr, and puts it into the search query. If you're going to fix it for Bob's Burgers, would you escape/omit all non alphanumeric characters? As that should pretty much clear it up for just about everything.

**Comment by zone117x** [comment]
This should be fixed now https://github.com/zone117x/Jackett/commit/56bbee2f1fe668167daa2c4631c8a3793e2f1616
